site_name: Myth of Yggdrasil — Wiki
site_url: https://mythofyggdrasil.github.io
repo_url: https://github.com/mythofyggdrasil/mythofyggdrasil.github.io

theme:
  name: material
  language: pt
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - toc.follow
    - content.code.copy
    - search.suggest
    - search.highlight
  palette:
    - scheme: default
      primary: blue
      accent: teal
      toggle:
        icon: material/brightness-7
        name: Modo escuro
    - scheme: slate
      primary: blue
      accent: teal
      toggle:
        icon: material/brightness-4
        name: Modo claro

plugins:
  - search

markdown_extensions:
  - toc:
      permalink: true
  - tables
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/copy-navi.js

nav:
  - Início: index.md
  - Introdução: introducao.md
  - Sistema:
    - Sistema e Diferenças: sistema.md
    - Novas Métricas: metricas.md
  - Personagem:
    - Jobs e Progressão: jobs.md
    - Guia de Up: guia-de-up.md
    - Omnibook: omnibook.md
  - Builds:
    - Builds e Guias de Classes: builds.md
    - Noviço: builds/novico.md
  - Mecânicas:
    - Todos os Reforges: todos-os-reforges.md
    - Cura e Sucos: cura.md
    - Pets: pets.md
    - Smart Cast: smart.md
    - Cartas: cartas.md
    - Singularidade e Encantamentos: singularidade.md
    - Durabilidade: durabilidade.md
  - Rankings:
    - Ranking de Equipamentos: ranking.md
  - Ferramentas:
    - Skill Calculator: tools/skill-calculator.md
    - Calculadora: tools/calculadora.md
  - Quests:
    - Quests de Chapéus: hat-quests.md
    - Quest de Comércio: quest-comercio.md
